### ISSUE TITLE
Longest Increasing Subsequence (LIS)

### ISSUE THREAD

**Issue by SoumyadeepMukherjee** [SoumyadeepMukherjee/Advanced-DSA#10]
Given an integer array nums, return the length of the longest strictly increasing subsequence.

**Comment by sarthak17jain** [comment]
Please assign me to this. I have written many algorithms both in Java and C++. I do leetcode regularly and am rated 1889 on it.
I will add both n^2 dp and nlogn binary search methods with detailed comments in each.

**Comment by sdeepanshu17** [comment]
I am willing to work on this.

**Comment by flow6979** [comment]
hello brother, can you please assign this to me as I am a competitive programmer and I would like to work on this repository. thank you.

**Comment by sarthak17jain** [comment]
@SoumyadeepMukherjee please accept my pull request.

**Comment by sarthak17jain** [comment]
@SoumyadeepMukherjee I worked really hard on this pull request please accept it. I added two methods instead of 1 for LIS. Please do justice to my hard work.
