### ISSUE TITLE
 Longest Substring Without Repeating Characters-Leetcode medium problem

### ISSUE THREAD

**Issue by kunalkabra46** [SoumyadeepMukherjee/Advanced-DSA#112]
hey @SoumyadeepMukherjee  please allow me to contribute to this issue...

please add hacktoberfest tag

**Comment by kunalkabra46** [comment]
I have made pull request...please look after it...

**Comment by abdul-sohail24** [comment]
hey @SoumyadeepMukherjee kindly assign this issue to me as I want to contribute.

**Comment by Arpit350** [comment]
Hey @SoumyadeepMukherjee Can you assigned this to me I have optimized approach for this Complexity- O(n)
