### ISSUE TITLE
Binary Search 

### ISSUE THREAD

**Issue by SoumyadeepMukherjee** [SoumyadeepMukherjee/Advanced-DSA#37]

**Comment by Arijit23** [comment]
please assign me this problem

**Comment by mehraankush** [comment]
i'm a 5 star coder i can make it happen..

**Comment by gaurav-iitb** [comment]
Please assign this to me

**Comment by Amulya77** [comment]
kindly assign me this issue I  already made a PR

**Comment by gemini30** [comment]
Requesting you to assign this problem to me

**Comment by NikhilCode12** [comment]
kindly assign this issue to me I have completed dsa you can see my leetcode profile here https://leetcode.com/Nikhilcode123/
i will write it efficiently and explain with graphical drawing as well, this can be my first contribution.

**Comment by Faizan96322** [comment]
@gemini30 hey, im new to hacktoberfest and to open-source contributions, I would really appreciate if you would assign me this task as this is a basic level task and would not require a lot of skill.
This would also help me with my first open source contributions and in hacktoberfest-22
