### ISSUE TITLE
find peak element using binary search

### ISSUE THREAD

**Issue by Amulya77** [SoumyadeepMukherjee/Advanced-DSA#42]
I have already made a PR #41 

This problem is similar to Local Minimum. And according to the given condition, num[i] != num[i+1], there must exist a O(logN) solution. So we use binary search for this problem.

If num[i-1] < num[i] > num[i+1], then num[i] is peak
If num[i-1] < num[i] < num[i+1], then num[i+1...n-1] must contains a peak
If num[i-1] > num[i] > num[i+1], then num[0...i-1] must contains a peak
If num[i-1] > num[i] < num[i+1], then both sides have peak
(n is num.length)

**Comment by Amulya77** [comment]
Kindly assign me this issue so that at least this will become my first contribution in hacktoberfest 22

**Comment by NikhilCode12** [comment]
kindly assign this issue to me i will write code efficiently in the given time complexity in cpp,java,python as well with graphical explanation as well , please assign this it is my first time contributing
