### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by Keerat666** [SoumyadeepMukherjee/Advanced-DSA#55]
Write a program to implement Binary Search in Kotlin

**Comment by Sandyy07** [comment]
Hi @SoumyadeepMukherjee ! I know Binary Search in Java .
Please assign me this issue. Looking forward for to work.

**Comment by PratyushSingh07** [comment]
Hi @SoumyadeepMukherjee , I know Kotlin as i develop apps in the said language
Please assign this issue to me
