### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by SoumyadeepMukherjee** [SoumyadeepMukherjee/Advanced-DSA#6]

**Comment by sarthak17jain** [comment]
Please assign me to this. I have written many algorithms both in Java and C++. I do leetcode regularly and am rated 1889 on it.
I will add easy to understand Heap Sort algorithm with comments.

**Comment by sdeepanshu17** [comment]
I am willing to work on this.

**Comment by sayandas722** [comment]
please assign me this

**Comment by Arijit23** [comment]
Please assign me this problem
