### ISSUE TITLE
Dijkstra's Algorithm

### ISSUE THREAD

**Issue by SoumyadeepMukherjee** [SoumyadeepMukherjee/Advanced-DSA#8]

**Comment by sarthak17jain** [comment]
Please assign me to this. I have written many algorithms both in Java and C++. I do leetcode regularly and am rated 1889 on it.

**Comment by sayandas722** [comment]
assign me

**Comment by Sandyy07** [comment]
Hi @SoumyadeepMukherjee ! Kindly Please assign me this issue. Looking forward for to work.
