### ISSUE TITLE
Tree traversals - inorder, preorder and postorder

### ISSUE THREAD

**Issue by SoumyadeepMukherjee** [SoumyadeepMukherjee/Advanced-DSA#87]
Write all tree traversals in java.

**Comment by aryanayush012** [comment]
if I am allowed to write in C++ ten assign this to me @SoumyadeepMukherjee

**Comment by Mikasa-Ackerman2074** [comment]
i can do this in java @SoumyadeepMukherjee

**Comment by SambariManikanta09** [comment]
Hello @SoumyadeepMukherjee,
I would like to implement these tree traversal techniques in java
I assure you to write a well-documented code follows the community guidelines
Please assign this to me 
Thank you

**Comment by SambariManikanta09** [comment]
I have raised a PR, and completed the following code requirement 
Please merge it 
Thank you
