### ISSUE TITLE
Longest Common Subsequence (LCS)

### ISSUE THREAD

**Issue by SoumyadeepMukherjee** [SoumyadeepMukherjee/Advanced-DSA#9]
Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.

**Comment by laxmanbalaraman** [comment]
Can you assign me this?

**Comment by vikash485** [comment]
Hey @SoumyadeepMukherjee, I can solve this issue in C++, can I work on it?

**Comment by laxmanbalaraman** [comment]
> Hey @SoumyadeepMukherjee, I can solve this issue in C++, can I work on it?

I am too doing this in C++ bro :)

**Comment by Subhadas2000** [comment]
please assign this to me

**Comment by vikash485** [comment]
@SoumyadeepMukherjee I have submitted a pr on this issue, please verify the same. Thank you

**Comment by Sandyy07** [comment]
Hi @SoumyadeepMukherjee ! I solve Longest Common Subsequence  in Java .
Please assign me this issue. Looking forward for to work.
